site_name: "laplax"
site_url: "https://laplax-org.github.io/laplax/"
repo_url: "https://github.com/laplax-org/laplax"
repo_name: "laplax-org/laplax"
strict: false

theme:
  name: "material"
  features:
    - navigation.sections # Section are shown in the sidebar
    - toc.integrate # Show table of contents on the left
    - header.autohide # Hide the header when scrolling down
  palette:
    scheme: default
    primary: teal
    accent: cyan
    toggle:
      icon: material/weather-sunny
      name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github # Github logo
    logo: "material/circle-opacity"

extra_javascript:
    # The below two make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - pymdownx.superfences  # Seems to enable syntax highlighting when used with the Material theme.
    - pymdownx.details  # Allowing hidden expandable regions denoted by ???

nav:
  - Home: index.md
  - Design Philosophy: design_philosophy.md
  - Examples:
    - Posterior GP Kernel: examples/0001_posterior_gp_kernel.ipynb
    - Laplace on MNIST: examples/0002_laplax_on_mnist.ipynb
  - API reference:
    - laplax.curv:
      - General: api/curv.md
      - Curvature: api/curv.curv.md
      - Approximations: api/curv.curv_approx.md
    - laplax.eval:
      - General: api/eval.md
      - Metrics: api/eval.metrics.md
      - Pushforward: api/eval.pushforward.md
      - Calibrate: api/eval.calibrate.md
    - laplax.util:
      - General: api/util.md
      - Flatten: api/util.flatten.md
      - Ops: api/util.ops.md
      - Tree: api/util.tree.md
      - MV: api/util.mv.md
      - Loader: api/util.loader.md
plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import pytkdocs_tweaks
            - pytkdocs_tweaks.main()
          options:
            show_root_heading: true
            #show_source: true
            members_order: source
            show_signature: true # Whether to show the full function signature
            separate_signature: true # Is not working; should separate function and signature to extra line.
            show_signature_annotations: true
            signature_crossrefs: true
            heading_style: "atx"
            docstring_style: "google"
            signature_style: "css"
            css_dir: "docs/css"
            heading_level: 4


  - mknotebooks:
      execute: false
      write_markdown: true
      enable_default_jupyter_cell_styling: true

extra_css:
  - css/custom.css
